### ISSUE TITLE
Encoding in hotstring expand section

### ISSUE THREAD

**Issue by kriskaminski** [RaptorX/AHK-ToolKit#4]
Hey. Great work. 
I have an issue with polish diacritics.  śćżłąę are replaced with sczlae. Is there any way to change encoding? Or where should I look and edit source files?

**Comment by kriskaminski** [comment]
It looks that only takes place in scintilla editor part (expand to or live code part). 
I tried changing LexAHKL dll to one form Scite4ahk, same effect.

What is more interesting, it worked properly once but I am not sure why...

**Comment by RaptorX** [comment]
fix will be available on the next release.
